#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v2
# autospec commit: e661f3a
#
Name     : R-QuickJSR
Version  : 1.0.8
Release  : 5
URL      : https://cran.r-project.org/src/contrib/QuickJSR_1.0.8.tar.gz
Source0  : https://cran.r-project.org/src/contrib/QuickJSR_1.0.8.tar.gz
Summary  : Interface for the 'QuickJS' Lightweight 'JavaScript' Engine
Group    : Development/Tools
License  : MIT
Requires: R-QuickJSR-lib = %{version}-%{release}
Requires: R-R6
Requires: R-Rcpp
Requires: R-jsonlite
BuildRequires : R-R6
BuildRequires : R-Rcpp
BuildRequires : R-jsonlite
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
The engine is bundled entirely within the package, requiring no external system
    dependencies beyond a 'C' compiler.

%package lib
Summary: lib components for the R-QuickJSR package.
Group: Libraries

%description lib
lib components for the R-QuickJSR package.


%prep
%setup -q -n QuickJSR

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1700989038

%install
export SOURCE_DATE_EPOCH=1700989038
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/QuickJSR/DESCRIPTION
/usr/lib64/R/library/QuickJSR/INDEX
/usr/lib64/R/library/QuickJSR/LICENSE
/usr/lib64/R/library/QuickJSR/Meta/Rd.rds
/usr/lib64/R/library/QuickJSR/Meta/features.rds
/usr/lib64/R/library/QuickJSR/Meta/hsearch.rds
/usr/lib64/R/library/QuickJSR/Meta/links.rds
/usr/lib64/R/library/QuickJSR/Meta/nsInfo.rds
/usr/lib64/R/library/QuickJSR/Meta/package.rds
/usr/lib64/R/library/QuickJSR/NAMESPACE
/usr/lib64/R/library/QuickJSR/R/QuickJSR
/usr/lib64/R/library/QuickJSR/R/QuickJSR.rdb
/usr/lib64/R/library/QuickJSR/R/QuickJSR.rdx
/usr/lib64/R/library/QuickJSR/help/AnIndex
/usr/lib64/R/library/QuickJSR/help/QuickJSR.rdb
/usr/lib64/R/library/QuickJSR/help/QuickJSR.rdx
/usr/lib64/R/library/QuickJSR/help/aliases.rds
/usr/lib64/R/library/QuickJSR/help/paths.rds
/usr/lib64/R/library/QuickJSR/html/00Index.html
/usr/lib64/R/library/QuickJSR/html/R.css
/usr/lib64/R/library/QuickJSR/include/cutils.h
/usr/lib64/R/library/QuickJSR/include/libbf.h
/usr/lib64/R/library/QuickJSR/include/libregexp-opcode.h
/usr/lib64/R/library/QuickJSR/include/libregexp.h
/usr/lib64/R/library/QuickJSR/include/libunicode-table.h
/usr/lib64/R/library/QuickJSR/include/libunicode.h
/usr/lib64/R/library/QuickJSR/include/list.h
/usr/lib64/R/library/QuickJSR/include/quickjs-atom.h
/usr/lib64/R/library/QuickJSR/include/quickjs-libc.h
/usr/lib64/R/library/QuickJSR/include/quickjs-opcode.h
/usr/lib64/R/library/QuickJSR/include/quickjs.h
/usr/lib64/R/library/QuickJSR/lib/libquickjs.a
/usr/lib64/R/library/QuickJSR/tests/testthat.R
/usr/lib64/R/library/QuickJSR/tests/testthat/test-JSContext.R
/usr/lib64/R/library/QuickJSR/tests/testthat/test-qjs_eval.R
/usr/lib64/R/library/QuickJSR/unicode_gen/unicode_gen.c
/usr/lib64/R/library/QuickJSR/unicode_gen/unicode_gen_def.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/QuickJSR/libs/QuickJSR.so
/usr/lib64/R/library/QuickJSR/libs/QuickJSR.so.avx2
/usr/lib64/R/library/QuickJSR/libs/QuickJSR.so.avx512
